"""empty message

Revision ID: 060b412223d4
Revises: 0dc3abc20cd9
Create Date: 2025-03-10 15:41:12.779185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '060b412223d4'
down_revision: Union[str, None] = '0dc3abc20cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nit', sa.Integer(), nullable=True),
    sa.Column('representante', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('por_iva', sa.Integer(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stm_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pop_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('administrador', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimensiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dimensiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dimensiones_nombre'), ['nombre'], unique=True)

    op.create_table('operacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operacion_nombre'), ['nombre'], unique=False)

    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tipo_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tipo_vehiculo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipo_vehiculo_nombre'), ['nombre'], unique=True)

    op.create_table('tarifas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.Column('operacion_id', sa.Integer(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensiones.id'], ),
    sa.ForeignKeyConstraint(['operacion_id'], ['operacion.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarifas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarifas_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarifas_operacion'), ['operacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarifas_tipo'), ['tipo'], unique=False)

    with op.batch_alter_table('clientel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), server_default=sa.text("'AC'"), nullable=False))

    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), server_default=sa.text("'AC'"), nullable=False))
        batch_op.create_index(batch_op.f('ix_contactos_nombres'), ['nombres'], unique=False)
        batch_op.create_unique_constraint(None, ['correo'])

    with op.batch_alter_table('leasingcli', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), server_default=sa.text("'AC'"), nullable=False))
        batch_op.add_column(sa.Column('tarifa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leasingcli_username'), ['username'], unique=False)
        batch_op.create_foreign_key(None, 'tarifas', ['tarifa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leasingcli', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leasingcli_username'))
        batch_op.drop_column('tarifa_id')
        batch_op.drop_column('estado')
        batch_op.drop_column('username')

    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_contactos_nombres'))
        batch_op.drop_column('estado')

    with op.batch_alter_table('clientel', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('ciudad')

    with op.batch_alter_table('tarifas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarifas_tipo'))
        batch_op.drop_index(batch_op.f('ix_tarifas_operacion'))
        batch_op.drop_index(batch_op.f('ix_tarifas_dimension'))

    op.drop_table('tarifas')
    with op.batch_alter_table('tipo_vehiculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipo_vehiculo_nombre'))

    op.drop_table('tipo_vehiculo')
    op.drop_table('servicio')
    op.drop_table('sector')
    with op.batch_alter_table('operacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operacion_nombre'))

    op.drop_table('operacion')
    with op.batch_alter_table('dimensiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dimensiones_nombre'))

    op.drop_table('dimensiones')
    op.drop_table('config_empresa')
    # ### end Alembic commands ###
