"""empty message

Revision ID: 2bd38d0a749e
Revises: 6814a4876bdf
Create Date: 2025-02-17 21:28:54.713957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2bd38d0a749e'
down_revision: Union[str, None] = '6814a4876bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.create_index(batch_op.f('ix_clientel_username'), ['username'], unique=False)

    with op.batch_alter_table('leasingcli', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usersesion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usersesion', ['usersesion_id'], ['id'])

    with op.batch_alter_table('usersesion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombrelogin', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.create_index(batch_op.f('ix_usersesion_nombrelogin'), ['nombrelogin'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersesion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usersesion_nombrelogin'))
        batch_op.drop_column('nombrelogin')

    with op.batch_alter_table('leasingcli', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usersesion_id')

    with op.batch_alter_table('clientel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientel_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
