"""empty message

Revision ID: 5fbed346e5a1
Revises: ada439b03ce9
Create Date: 2025-03-19 18:09:52.756075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5fbed346e5a1'
down_revision: Union[str, None] = 'ada439b03ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leasingcli', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagenplaca', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leasingcli', schema=None) as batch_op:
        batch_op.drop_column('imagenplaca')

    # ### end Alembic commands ###
