"""empty message

Revision ID: dd1ae691d23d
Revises: 268b93078240
Create Date: 2026-04-28 12:48:59.965854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dd1ae691d23d'
down_revision: Union[str, None] = '268b93078240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leasingcli', schema=None) as batch_op:
        batch_op.alter_column('usersesion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tarifa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tarifas', schema=None) as batch_op:
        batch_op.alter_column('dimension_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('operacion_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usersesion', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersesion', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tarifas', schema=None) as batch_op:
        batch_op.alter_column('operacion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('dimension_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('leasingcli', schema=None) as batch_op:
        batch_op.alter_column('tarifa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usersesion_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
