"""empty message

Revision ID: ecb416d1152c
Revises: 060b412223d4
Create Date: 2025-03-10 16:06:53.709969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb416d1152c'
down_revision: Union[str, None] = '060b412223d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientel', schema=None) as batch_op:
        batch_op.drop_constraint('clientel_email_key', type_='unique')
        batch_op.drop_index('ix_clientel_email')

    with op.batch_alter_table('dimensiones', schema=None) as batch_op:
        batch_op.drop_constraint('dimensiones_nombre_key', type_='unique')

    with op.batch_alter_table('operacion', schema=None) as batch_op:
        batch_op.drop_constraint('operacion_nombre_key', type_='unique')

    with op.batch_alter_table('tarifas', schema=None) as batch_op:
        batch_op.drop_index('ix_tarifas_dimension')
        batch_op.create_index(batch_op.f('ix_tarifas_dimension'), ['dimension'], unique=False)
        batch_op.drop_index('ix_tarifas_operacion')
        batch_op.create_index(batch_op.f('ix_tarifas_operacion'), ['operacion'], unique=False)

    with op.batch_alter_table('tipo_vehiculo', schema=None) as batch_op:
        batch_op.drop_constraint('tipo_vehiculo_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_vehiculo', schema=None) as batch_op:
        batch_op.create_unique_constraint('tipo_vehiculo_nombre_key', ['nombre'])

    with op.batch_alter_table('tarifas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarifas_operacion'))
        batch_op.create_index('ix_tarifas_operacion', ['operacion', 'tipo'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tarifas_dimension'))
        batch_op.create_index('ix_tarifas_dimension', ['dimension', 'tipo', 'operacion'], unique=False)

    with op.batch_alter_table('operacion', schema=None) as batch_op:
        batch_op.create_unique_constraint('operacion_nombre_key', ['nombre'])

    with op.batch_alter_table('dimensiones', schema=None) as batch_op:
        batch_op.create_unique_constraint('dimensiones_nombre_key', ['nombre'])

    with op.batch_alter_table('clientel', schema=None) as batch_op:
        batch_op.create_index('ix_clientel_email', ['email'], unique=False)
        batch_op.create_unique_constraint('clientel_email_key', ['email'])

    # ### end Alembic commands ###
